<?php
/*
 * Copyright (c) 2014 Eltrino LLC (http://eltrino.com)
 *
 * Licensed under the Open Software License (OSL 3.0).
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://opensource.org/licenses/osl-3.0.php
 *
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@eltrino.com so we can send you a copy immediately.
 */
namespace Diamante\DeskBundle\Form\Type;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;
use Symfony\Component\Form\FormEvent;
use Symfony\Component\Form\FormEvents;

class BranchType extends AbstractType
{
    /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder->add(
            'name',
            'text',
            array(
                'label'    => 'diamante.desk.attributes.name',
                'required' => true,
            )
        );

        $builder->addEventListener(FormEvents::PRE_SET_DATA, function (FormEvent $event) {
            $branch = $event->getData();
            $form = $event->getForm();
            // check if the Branch object is "new"
            // If no data is passed to the form, the data is "null".
            // This should be considered a new "Branch"
            if (!$branch || null === $branch->id) {
                $form->add(
                    'key',
                    'text',
                    array(
                        'label'    => 'diamante.desk.attributes.key',
                        'required' => false,
                        'tooltip'  => 'Leave empty to be autogenerated from Branch Name.'
                    )
                );
            } else {
                $form->add(
                    'key',
                    'hidden',
                    array(
                        'data'    => '0'
                    )
                );
            }
        });

        $builder->add(
            'description',
            'textarea',
            array(
                'label'    => 'diamante.desk.common.description',
                'required' => false,
            )
        );

        $builder->add(
            'logoFile',
            'file',
            array(
                'label'    => 'diamante.desk.attachment.image',
                'required' => false,
                'tooltip'  => '"JPEG" and "PNG" image formats are supported only.'
            )
        );

        $builder->add(
            'defaultAssignee',
            'diamante_assignee_select',
            array(
                'label'    => 'diamante.desk.attributes.assignee',
                'required' => false
            )
        );

        // tags
        $builder->add(
            'tags',
            'oro_tag_select',
            array(
                'label' => 'oro.tag.entity_plural_label'
            )
        );

        // Branch Email Configuration
        $builder->add(
            'branch_email_configuration',
            new BranchEmailConfigurationType()
        );

    }

    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(
            array(
                'data_class' => 'Diamante\DeskBundle\Api\Command\BranchCommand',
                'intention' => 'branch',
                'cascade_validation' => true
            )
        );
    }

    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return 'diamante_branch_form';
    }
}
