datagrids:
  diamante-automation-event-triggered-grid:
    source:
      type: orm
      query:
        select:
          - w.id
          - w.name
          - w.status
          - ('event_triggered') as type
        from:
          - { table: %diamante_automation.event_triggered_rule.entity.class%, alias: w}

    properties:
      id: ~
      type: ~

      view_link:
        type: url
        route: diamante_event_triggered_view
        params: [type, id]

      update_link:
        type: url
        route: diamante_event_triggered_update
        params: [type, id]

      delete_link:
        type: url
        route: diamante_event_triggered_delete
        params: [type, id]

    sorters:
      columns:
        name:
          data_name: w.name
        status:
          data_name: w.status

    filters:
      columns:
        name:
          type: string
          data_name: w.name

    columns:
      name:
        label: diamante.automation.common.name
      status:
        label: diamante.automation.attributes.status
        frontend_type: select
        choices:
          0: diamante.automation.rule.status.inactive
          1: diamante.automation.rule.status.active

    actions:
      view:
        type: navigate
        label: diamante.automation.rule.actions.view
        icon: eye-open
        link: view_link
        rowAction: true
        acl_resource: VIEW;Entity:DiamanteAutomationBundle:EventTriggeredRule
      update:
        type: navigate
        label: diamante.automation.rule.actions.edit
        icon: edit
        link: update_link
        rowAction: true
        acl_resource: EDIT;Entity:DiamanteAutomationBundle:EventTriggeredRule
      delete:
        type: delete
        label: diamante.automation.rule.actions.delete
        icon: trash
        link: delete_link
        acl_resource: DELETE;Entity:DiamanteAutomationBundle:EventTriggeredRule

    mass_actions:
      delete:
        type: delete
        label: diamante.automation.rule.actions.mass.remove
        acl_resource: DELETE;Entity:DiamanteAutomationBundle:EventTriggeredRule
        entity_name: DiamanteAutomationBundle:EventTriggeredRule
        data_identifier: w.id
        icon: trash
      deactivate_rule:
        type: deactivate_rule
        label: diamante.automation.rule.actions.mass.deactivate
        acl_resource: EDIT;Entity:DiamanteAutomationBundle:EventTriggeredRule
        entity_name: DiamanteAutomationBundle:EventTriggeredRule
        data_identifier: w.id
        icon: remove
      activate_rule:
        type: activate_rule
        label: diamante.automation.rule.actions.mass.activate
        acl_resource: EDIT;Entity:DiamanteAutomationBundle:EventTriggeredRule
        entity_name: DiamanteAutomationBundle:EventTriggeredRule
        data_identifier: w.id
        icon: check

  diamante-automation-time-triggered-grid:
    source:
      type: orm
      query:
        select:
          - b.id
          - b.name
          - b.timeInterval as time
          - b.status
          - ('time_triggered') as type
        from:
          - { table: %diamante_automation.time_triggered_rule.entity.class%, alias: b}

    properties:
      id: ~
      type: ~

      view_link:
        type: url
        route: diamante_time_triggered_view
        params: [type, id]

      update_link:
        type: url
        route: diamante_time_triggered_update
        params: [type, id]

      delete_link:
        type: url
        route: diamante_time_triggered_delete
        params: [type, id]

    sorters:
      columns:
        name:
          data_name: b.name
        status:
          data_name: b.status

    filters:
      columns:
        name:
          type: string
          data_name: b.name

    columns:
      name:
        label: diamante.automation.common.name
      time:
        label: diamante.automation.rule.time_triggered.repetition_time
        frontend_type: select
        choices: '@diamante_automation.datagrid.helper->getTimeIntervalChoices'

      status:
        label: diamante.automation.attributes.status
        frontend_type: select
        choices:
          0: diamante.automation.rule.status.inactive
          1: diamante.automation.rule.status.active

    actions:
      view:
        type: navigate
        label: diamante.automation.rule.actions.view
        icon: eye-open
        link: view_link
        rowAction: true
        acl_resource: VIEW;Entity:DiamanteAutomationBundle:TimeTriggeredRule
      update:
        type: navigate
        label: diamante.automation.rule.actions.edit
        icon: edit
        link: update_link
        rowAction: true
        acl_resource: EDIT;Entity:DiamanteAutomationBundle:TimeTriggeredRule
      delete:
        type: delete
        label: diamante.automation.rule.actions.delete
        icon: trash
        link: delete_link
        acl_resource: DELETE;Entity:DiamanteAutomationBundle:TimeTriggeredRule

    mass_actions:
      delete:
        type: delete
        label: diamante.automation.rule.actions.mass.remove
        acl_resource: DELETE;Entity:DiamanteAutomationBundle:TimeTriggeredRule
        entity_name: DiamanteAutomationBundle:TimeTriggeredRule
        data_identifier: b.id
        icon: trash
      deactivate_rule:
        type: deactivate_rule
        label: diamante.automation.rule.actions.mass.deactivate
        acl_resource: EDIT;Entity:DiamanteAutomationBundle:TimeTriggeredRule
        entity_name: DiamanteAutomationBundle:TimeTriggeredRule
        data_identifier: b.id
        icon: remove
      activate_rule:
        type: activate_rule
        label: diamante.automation.rule.actions.mass.activate
        acl_resource: EDIT;Entity:DiamanteAutomationBundle:TimeTriggeredRule
        entity_name: DiamanteAutomationBundle:TimeTriggeredRule
        data_identifier: b.id
        icon: check
