diamante_automation:
  entities: []

  conditions:
    eq:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Eq'
      frontend_label: diamante.automation.condition.eq
    neq:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Neq'
      frontend_label: diamante.automation.condition.neq
    gt:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Gt'
      frontend_label: diamante.automation.condition.gt
    gte:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Gte'
      frontend_label: diamante.automation.condition.gte
    lt:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Lt'
      frontend_label: diamante.automation.condition.lt
    lte:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Lte'
      frontend_label: diamante.automation.condition.lte
    like:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Like'
      frontend_label: diamante.automation.condition.contains
      type: 'string'
    not_like:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\NotLike'
      frontend_label: diamante.automation.condition.not_contains
      type: 'string'
    created:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Created'
      frontend_label: diamante.automation.condition.created
      type: 'bool'
    updated:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Updated'
      frontend_label: diamante.automation.condition.updated
      type: 'bool'
    removed:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Removed'
      frontend_label: diamante.automation.condition.removed
      type: 'bool'
    changed:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\Changed'
      frontend_label: diamante.automation.condition.changed
      type: 'bool'
      rules: ['event_triggered']
    changed_from:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\ChangedFrom'
      frontend_label: diamante.automation.condition.changed_from
      rules: ['event_triggered']
    changed_to:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\ChangedTo'
      frontend_label: diamante.automation.condition.changed_to
      rules: ['event_triggered']
    'true':
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\TrueCondition'
      frontend_label: diamante.automation.condition.true
    'false':
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\FalseCondition'
      frontend_label: diamante.automation.condition.false
    is_customer:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\IsCustomer'
      frontend_label: diamante.automation.condition.customer
      type: 'bool'
    is_admin:
      class: 'Diamante\AutomationBundle\Rule\Condition\Expression\IsAdmin'
      frontend_label: diamante.automation.condition.admin
      type: 'bool'


  actions:
    update_property:
      id: @diamante_automation.action.update_property
      frontend_label: diamante.automation.action.update_property
      frontend_options:
        source: "@diamante.autocomplete.user.service->getAssigners"
      data_types: ['*', '!user', '!users']
    notify_by_email:
      id: @diamante_automation.action.notify_by_email
      frontend_label: diamante.automation.action.notify_by_email
      frontend_options:
        source: "@diamante.autocomplete.user.service->getNotifyActionList"
      data_types: ['*']